### ISSUE TITLE
Pip install = AttributeError: module 'numpy' has no attribute 'warnings'.  (and fix)

### ISSUE THREAD

**Issue by Oil3** [cloudmercato/ai-benchmark#2]
TF Version: 2.13.0-rc1
Platform: macOS-14.1.1-arm64-arm-64bit (M1 pro max)
Python: 3.11.6
Numpy: 1.26.2
AND
*  TF Version: 2.15.0
*  Platform: macOS-14.1.2-arm64-arm-64bit (M2 macbook air)

```
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> np.warnings.filterwarnings('ignore')
KeyboardInterrupt
>>> from ai_benchmark import AIBenchmark
>>> results = AIBenchmark().run()

>>   AI-Benchmark-v.0.1.2
>>   Let the AI Games begin..

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/ai_benchmark/__init__.py", line 18, in __init__
    np.warnings.filterwarnings('ignore')
    ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'. Did you mean: 'hanning'?
```
**I Installed via pip3**
Came from the website, manually looked for github rep (no link), found latest commit "@ZuluPro ZuluPro Removed numpy.warnings" 

manually remoed np.warnings on line 18.
Spent 30minutes removing .pyc cache here and there still experiencing same issue, uninstalled and reinstalled numpy then app and now the benchmark works and is running.

**FIX: remove _/ai_benchmark/__init__.py line 18_ just as commit 6fb99ed, remove its corresponding pycache, and if not enough uninstall/reinstall app/numpy**

PS: also tested same issue.outcome on mcair M2 silicon mac machines
pps: the m2 macbook air is extraordinary, but the M1promax obliterates it in anything graphical/AI from my experience, so much that I ssh into the mcpro to do my stuff. waiting for the results on both

**Comment by vsoch** [comment]
It looks like the code no longer has this (although the pip install does) but maybe this would work?

```diff
- np.warnings.filterwarnings('ignore')
+ np.seterr(all='ignore')
```

**Comment by Oil3** [comment]
I dont remember much, but it seems I had done this:
> FIX: remove _/ai_benchmark/**init**.py line 18_ just as commit [6fb99ed](https://github.com/cloudmercato/ai-benchmark/commit/6fb99edd580b22e079d8b85e90b3eeaec4bf50fe), remove its corresponding pycache, and if not enough uninstall/reinstall app/numpy

**Comment by vsoch** [comment]
@Oil3 did you ever test this on more than one GPU or node? I ran the benchmark today on one node, one GPU and only one test didn't run (a verison of keras too new) and I'm wondering if it can extend beyond that. From a quick glance it seems like maybe it would work on >1 GPU but not more than one node?
